version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: truphish-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    container_name: truphish-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
