version: '3.8'

services:
  ml-service:
    build:
      context: ./ml-service
    container_name: truphish-ml-service
    restart: always
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
    container_name: truphish-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - ML_API_URL=http://ml-service:8000
    depends_on:
      - ml-service

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    container_name: truphish-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
